---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin/' state='directory'

  roles:
    - {role: gcp, tags: ['gcp', 'cloud']}
    - {role: idea, tags: ['idea', 'editor']}
    - {role: latex, tags: ['latex', 'markup']}
    - {role: groovy, tags: ['groovy', 'language']}
    - {role: python, tags: ['python', 'language']}
    - {role: typescript, tags: ['typescript', 'language']}
