---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin/' state='directory'

  roles:
    # documents {{{
    - {role: latex, tags: ['latex', 'docs']}
    - {role: graphviz, tags: ['graphviz', 'docs']}
    - {role: plantuml, tags: ['plantuml', 'docs']}
    - {role: sphinx, tags: ['sphinx', 'docs']}
    # }}}
    # languages {{{
    - {role: clang, tags: ['clang', 'lang']}
    - {role: groovy, tags: ['groovy', 'lang']}
    - {role: hylang, tags: ['hylang', 'lang']}
    - {role: nimlang, tags: ['nimlang', 'lang']}
    - {role: python, tags: ['python', 'lang']}
    - {role: science, tags: ['science', 'lang']}
    # }}}
    # services {{{
    - {role: docker, tags: ['docker', 'serv']}
    - {role: gcloud, tags: ['gcloud', 'serv']}
    - {role: mongodb, tags: ['mongodb', 'serv']}
    - {role: redis, tags: ['redis', 'serv']}
    # }}}
