---
- hosts: 127.0.0.1
  connection: local
  pre_tasks:
  - name: ensure ~/.local/bin/
    file:
      name: ~/.local/bin/
      state: directory
      mode: 0750
    tags: [pre]
  - name: ensure pipx
    package:
      name: pipx
    become: true
    tags: [pre]
  roles:
    - {role: clang, tags: ['clang']}
    # - {role: clojure, tags: ['clojure']}
    # - {role: docker, tags: ['docker']}
    # - {role: elixir, tags: ['elixir']}
    # - {role: gcloud, tags: ['gcloud']}
    # - {role: golang, tags: ['golang']}
    - {role: graphviz, tags: ['graphviz']}
    # - {role: groovy, tags: ['groovy']}
    # - {role: haskell, tags: ['haskell']}
    # - {role: hylang, tags: ['hylang']}
    # - {role: java, tags: ['java']}
    # - {role: julia, tags: ['julia']}
    - {role: jupyter, tags: ['jupyter']}
    # - {role: kaggle, tags: ['kaggle']}
    # - {role: latex, tags: ['latex']}
    # - {role: nim, tags: ['nim']}
    - {role: nodejs, tags: ['nodejs']}
    - {role: plantuml, tags: ['plantuml']}
    - {role: python, tags: ['python']}
    # - {role: racket, tags: ['racket']}
    # - {role: rlang, tags: ['rlang']}
    # - {role: shell, tags: ['shell']}
    # - {role: sphinx, tags: ['sphinx']}
    # - {role: sql, tags: ['sql']}
  environment:
    LANG: en_US.UTF-8
    PATH: "{{ ansible_env.HOME }}/.local/bin/:{{ ansible_env.PATH }}"
