---

- hosts: localhost

  pre_tasks:

  - name: create ~/bin directory
    file: name='~/bin' state='directory'
    tags: ['pre', 'directory']

  roles:
    - {role: clang, tags: ['clang', 'system']}
    - {role: graphviz, tags: ['graphviz', 'markup']}
    - {role: latex, tags: ['latex', 'markup']}
    - {role: plantuml, tags: ['plantuml', 'markup']}
    - {role: python, tags: ['python', 'script']}
