---

- hosts: localhost

  pre_tasks:

  - name: prepare npm
    package: name='npm'
    become: true

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin' state='directory'

  roles:
    # cloud
    - {role: google, tags: ['google', 'cloud']}
    # editor
    - {role: jupyterlab, tags: ['jupyterlab', 'editor']}
    - {role: spacemacs, tags: ['spacemacs', 'editor']}
    # markup
    - {role: graphviz, tags: ['graphviz', 'markup']}
    - {role: plantuml, tags: ['plantuml', 'markup']}
    - {role: texlive, tags: ['texlive', 'markup']}
    - {role: text, tags: ['text', 'markup']}
    # language
    - {role: hylang, tags: ['hylang', 'language']}
    - {role: python, tags: ['python', 'language']}
