---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin/' state='directory'

  roles:
    - {role: clang, tags: ['clang']}
    - {role: docker, tags: ['docker']}
    - {role: gcloud, tags: ['gcloud']}
    - {role: groovy, tags: ['groovy']}
    - {role: hylang, tags: ['hylang']}
    - {role: latex, tags: ['latex']}
    - {role: plantuml, tags: ['plantuml']}
    - {role: python, tags: ['python']}
