---

- hosts: localhost

  pre_tasks:

  - name: ensure ~/Scripts
    file:
      name: ~/Scripts
      state: directory
    tags: user

  - name: ensure pip3
    package:
      name: python3-pip
    become: true
    tags: admin

  roles:
    - {role: clang, tags: ['clang', 'language']}
    # - {role: clojure, tags: ['clojure', 'language']}
    # - {role: docker, tags: ['docker', 'docker']}
    # - {role: elixir, tags: ['elixir', 'language']}
    # - {role: gcloud, tags: ['gcloud', 'cloud']}
    # - {role: golang, tags: ['golang', 'language']}
    - {role: graphviz, tags: ['graphviz', 'document']}
    # - {role: groovy, tags: ['groovy', 'language']}
    # - {role: haskell, tags: ['haskell', 'language']}
    # - {role: hylang, tags: ['hylang', 'language']}
    # - {role: java, tags: ['java', 'language']}
    # - {role: julia, tags: ['julia', 'language']}
    - {role: jupyter, tags: ['jupyter', 'editor']}
    - {role: kaggle, tags: ['kaggle', 'cloud']}
    # - {role: latex, tags: ['latex', 'document']}
    - {role: markdown, tags: ['markdown', 'document']}
    # - {role: mongodb, tags: ['mongodb', 'database']}
    # - {role: nim, tags: ['nim', 'language']}
    # - {role: nodejs, tags: ['nodejs', 'language']}
    # - {role: plantuml, tags: ['plantuml', 'document']}
    - {role: python, tags: ['python', 'language']}
    # - {role: racket, tags: ['racket', 'language']}
    # - {role: redis, tags: ['redis', 'database']}
    # - {role: rlang, tags: ['rlang', 'language']}
    # - {role: robot, tags: ['robot', 'automation']}
    # - {role: ruby, tags: ['ruby', 'language']}
    # - {role: shell, tags: ['shell', 'language']}
    # - {role: sphinx, tags: ['sphinx', 'document']}
    # - {role: tensorflow, tags: ['sphinx', 'framework']}

  environment:
    LANG: en_US.UTF-8
    PATH: "{{ ansible_env.HOME }}/.local/bin/:{{ ansible_env.PATH }}"
