---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin/' state='directory'

  roles:
    - {role: clang, tags: ['clang']}
    - {role: clojure, tags: ['clojure']}
    - {role: cuda, tags: ['cuda']}
    - {role: docker, tags: ['docker']}
    - {role: elixir, tags: ['elixir']}
    - {role: gcloud, tags: ['gcloud']}
    - {role: golang, tags: ['golang']}
    - {role: groovy, tags: ['groovy']}
    - {role: haskell, tags: ['haskell']}
    - {role: hylang, tags: ['hylang']}
    - {role: idea, tags: ['idea']}
    - {role: java, tags: ['java']}
    - {role: julia, tags: ['julia']}
    - {role: latex, tags: ['latex']}
    - {role: manim, tags: ['manim']}
    - {role: nim, tags: ['nim']}
    - {role: plantuml, tags: ['plantuml']}
    - {role: python, tags: ['python']}
    - {role: racket, tags: ['racket']}
    - {role: rlang, tags: ['rlang']}
    - {role: typescript, tags: ['typescript']}
    - {role: vscode, tags: ['vscode']}
