---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin/' state='directory'

  roles:
    - {role: clang, tags: ['clang']}
    - {role: graphviz, tags: ['graphviz']}
    - {role: jupyter, tags: ['jupyter']}
    - {role: plantuml, tags: ['plantuml']}
    - {role: python, tags: ['python']}
    - {role: sphinx, tags: ['sphinx']}
    - {role: vscode, tags: ['vscode']}
