---

- hosts: localhost

  pre_tasks:

  - name: create ~/bin directory
    file: name='~/bin' state='directory'
    tags: ['pre', 'directory']

  roles:
    - {role: clang, tags: ['clang']}
    - {role: code, tags: ['code']}
    - {role: gcp, tags: ['gcp']}
    - {role: python, tags: ['python']}
    - {role: typescript, tags: ['typescript']}
