---

- hosts: localhost

  pre_tasks:

  - name: create ~/bin directory
    file: name='~/bin' state='directory'
    tags: ['pre', 'directory']

  roles:
    - {role: clang, tags: ['clang']}
    - {role: nodejs, tags: ['nodejs']}
    - {role: python, tags: ['python']}
    - {role: text, tags: ['text']}
