---

- hosts: localhost

#ROLES{{{
  roles:
      - { role: fmind.clang, become: true, tags: ['sys', 'clang'] }
      - { role: fmind.clojure, become: true, tags: ['sys', 'clojure'] }
      - { role: fmind.elixir, become: true, tags: ['sys', 'elixir'] }
      - { role: fmind.golang, become: true, tags: ['sys', 'golang'] }
      - { role: fmind.graphviz, become: true, tags: ['sys', 'graphviz'] }
      - { role: fmind.groovy, become: true, tags: ['sys', 'groovy'] }
      - { role: fmind.haskell, become: true, tags: ['sys', 'haskell'] }
      - { role: fmind.java, become: true, tags: ['sys', 'java'] }
      - { role: fmind.julia, become: true, tags: ['sys', 'julia'] }
      - { role: fmind.nodejs, become: true, tags: ['sys', 'nodejs'] }
      - { role: fmind.plantuml, become: true, tags: ['sys', 'plantuml'] }
      - { role: fmind.python, become: true, tags: ['sys', 'python'] }
      - { role: fmind.rlang, become: true, tags: ['sys', 'rlang'] }
#}}}
  tasks:
#CLOJURE{{{
  - name: create lein dir
    file: path='~/.lein/' state='directory'
    tags: ['usr', 'clojure']

  - name: create boot dir
    file: path='~/.boot/' state='directory'
    tags: ['usr', 'clojure']

  - name: deploy lein conf
    file: src='{{playbook_dir}}/clojure/profiles.clj' dest='~/.lein/profiles.clj' state=link force=yes
    tags: ['usr', 'clojure']

  - name: deploy boot conf
    file: src='{{playbook_dir}}/clojure/profile.boot' dest='~/.boot/profile.boot' state=link force=yes
    tags: ['usr', 'clojure']

  - name: deploy boot prop
    file: src='{{playbook_dir}}/clojure/boot.properties' dest='~/.boot/boot.properties' state=link force=yes
    tags: ['usr', 'clojure']
#}}}
#ELIXIR{{{
  - name: deploy elixir conf
    file: src='{{playbook_dir}}/elixir/iex.exs' dest='~/.iex.exs' state=link force=yes
    tags: ['usr', 'elixir']
#}}}
#HASKELL{{{
  - name: create stack dir
    file: path='~/.stack/' state='directory'
    tags: ['usr', 'haskell']

  - name: deploy stack conf
    file: src='{{playbook_dir}}/haskell/config.yaml' dest='~/.stack/config.yaml' state=link force=yes
    tags: ['usr', 'haskell']

  - name: deploy haskeline conf
    file: src='{{playbook_dir}}/haskell/haskeline' dest='~/.haskeline' state=link force=yes
    tags: ['usr', 'haskell']
#}}}
#JULIA{{{
  - name: deploy julia conf
    file: src='{{playbook_dir}}/julia/juliarc.jl' dest='~/.juliarc.jl' state=link force=yes
    tags: ['usr', 'julia']
#}}}
#NODEJS{{{
  - name: deploy npm config
    file: src='{{playbook_dir}}/nodejs/npmrc' dest='~/.npmrc' state=link force=yes
    tags: ['usr', 'nodejs']
#}}}
#PYTHON{{{
  - name: install python tool
    pip: name='{{item}}' executable='pip3' extra_args='--user'
    with_items:
      - jedi
      - yapf
      - isort
      - pipenv
      - flake8
      - neovim
      - autoflake
      - pipenv-pipes
    tags: ['usr', 'python']

  - name: install python shell
    pip: name='{{item}}' executable='pip3' extra_args='--user'
    with_items:
      - hy
      - ipython
      - ptpython
      - trypackage
    tags: ['usr', 'python']

  - name: deploy pip conf
    file: src='{{playbook_dir}}/python/pypirc' dest='~/.pypirc' state=link force=yes
    tags: ['usr', 'python']

  - name: create try dir
    file: path='~/.config/try' state=directory
    tags: ['usr', 'python']

  - name: deploy try conf
    file: src='{{playbook_dir}}/python/try.ini' dest='~/.config/try/config.ini' state=link force=yes
    tags: ['usr', 'python']

  - name: create yapf dir
    file: path='~/.config/yapf' state=directory
    tags: ['usr', 'python']

  - name: deploy yapf conf
    file: src='{{playbook_dir}}/python/yapf' dest='~/.config/yapf/style' state=link force=yes
    tags: ['usr', 'python']

  - name: create ipython dir
    shell: ~/.local/bin/ipython profile create default
    args:
        executable: /bin/bash
    tags: ['usr', 'python']

  - name: deploy ipython conf
    file: src='{{playbook_dir}}/python/ipython_config.py' dest='~/.ipython/profile_default/ipython_config.py' state=link force=yes
    tags: ['usr', 'python']

  - name: create ptpython dir
    file: path='~/.ptpython' state=directory
    tags: ['usr', 'python']

  - name: deploy ptpython conf
    file: src='{{playbook_dir}}/python/ptpython.py' dest='~/.ptpython/config.py' state=link force=yes
    tags: ['usr', 'python']

#}}}
#RACKET{{{
  - name: deploy racket conf
    file: src='{{playbook_dir}}/racket/racketrc' dest='~/.racketrc' state=link force=yes
    tags: ['usr', 'racket']
#}}}
#RLANG{{{
  - name: deploy rlang conf
    file: src='{{playbook_dir}}/rlang/Rprofile' dest='~/.Rprofile' state=link force=yes
    tags: ['usr', 'rlang']
#}}}
