---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin/' state='directory'

  roles:
#   - {role: clang, tags: ['clang']}
#   - {role: latex, tags: ['latex']}
#   - {role: python, tags: ['python']}
#   - {role: science, tags: ['science']}
