---

- hosts: localhost

  pre_tasks:

  - name: pip
    package:
      name: python3-pip
    become: true
    tags: admin

  - name: ~/bin/
    file:
      name: ~/bin
      state: directory

  roles:
    # clouds {{{
    - {role: gcloud, tags: ['gcloud', 'cloud']}
    # }}}
    # editors {{{
    # - {role: emacs, tags: ['emacs', 'edit']}
    # - {role: intellij, tags: ['intellij', 'edit']}
    - {role: jupyter, tags: ['jupyter', 'edit']}
    - {role: neovim, tags: ['neovim', 'edit']}
    # - {role: vscode, tags: ['vscode', 'edit']}
    # }}}
    # documents {{{
    - {role: graphviz, tags: ['graphviz', 'docs']}
    # - {role: latex, tags: ['latex', 'docs']}
    - {role: plantuml, tags: ['plantuml', 'docs']}
    - {role: sphinx, tags: ['sphinx', 'docs']}
    # }}}
    # languages {{{
    - {role: clang, tags: ['clang', 'lang']}
    # - {role: clojure, tags: ['clojure', 'lang']}
    # - {role: elixir, tags: ['elixir', 'lang']}
    # - {role: golang, tags: ['golang', 'lang']}
    # - {role: groovy, tags: ['groovy', 'lang']}
    # - {role: haskell, tags: ['haskell', 'lang']}
    - {role: hylang, tags: ['hylang', 'lang']}
    # - {role: java, tags: ['java', 'lang']}
    # - {role: julia, tags: ['julia', 'lang']}
    # - {role: nimlang, tags: ['nimlang', 'lang']}
    # - {role: nodejs, tags: ['nodejs', 'lang']}
    - {role: python, tags: ['python', 'lang']}
    # - {role: racket, tags: ['racket', 'lang']}
    # - {role: rlang, tags: ['rlang', 'lang']}
    # }}}
    # services {{{
    - {role: docker, tags: ['docker', 'serve']}
    - {role: mongodb, tags: ['mongodb', 'serve']}
    - {role: redis, tags: ['redis', 'serve']}
    # }}}
    # software {{{
    # - {role: amc, tags: ['amc', 'soft']}
    - {role: kivy, tags: ['kivy', 'soft']}
    - {role: tensorflow, tags: ['tensorflow', 'soft']}
    # }}}
