---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin/' state='directory'

  roles:
    # editor
    - {role: emacs, tags: ['emacs', 'editor']}
    - {role: jupyter, tags: ['jupyter', 'editor']}
    # markup
    - {role: graphviz, tags: ['graphviz', 'markup']}
    - {role: plantuml, tags: ['plantuml', 'markup']}
    - {role: latex, tags: ['latex', 'markup']}
    - {role: text, tags: ['text', 'markup']}
    # language
    - {role: clang, tags: ['clang', 'language']}
    - {role: hylang, tags: ['hylang', 'language']}
    - {role: python, tags: ['python', 'language']}
    - {role: racket, tags: ['racket', 'language']}
    - {role: clojure, tags: ['clojure', 'language']}
