---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin/' state='directory'

  roles:
    # editors
    - {role: jupyter, tags: ['jupyter', 'edit']}
    # documents
    - {role: latex, tags: ['latex', 'docs']}
    - {role: plantuml, tags: ['plantuml', 'docs']}
    # languages
    - {role: clang, tags: ['clang', 'lang']}
    - {role: hylang, tags: ['hylang', 'lang']}
    - {role: python, tags: ['python', 'lang']}
    # services
    - {role: docker, tags: ['docker', 'serv']}
    - {role: gcloud, tags: ['gcloud', 'serv']}
