---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin/' state='directory'

  roles:
    - {role: latex, tags: ['latex', 'markup']}
    - {role: gcloud, tags: ['gcloud', 'cloud']}
    - {role: vscode, tags: ['vscode', 'editor']}
    - {role: python, tags: ['python', 'language']}
    - {role: tscript, tags: ['tscript', 'language']}
