---

- hosts: localhost

  pre_tasks:

  - name: create ~/bin directory
    file: name='~/bin' state='directory'
    tags: ['pre', 'directory']

  roles:
    - {role: cuda, tags: ['cuda']}
    - {role: clang, tags: ['clang']}
    - {role: latex, tags: ['latex']}
    - {role: prose, tags: ['prose']}
    - {role: python, tags: ['python']}
