---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin/' state='directory'

  roles:
    - {role: clojure, tags: ['clojure']}
    - {role: emacs, tags: ['emacs']}
    - {role: graphviz, tags: ['graphviz']}
    - {role: hylang, tags: ['hylang']}
    - {role: latex, tags: ['latex']}
    - {role: plantuml, tags: ['plantuml']}
    - {role: python, tags: ['python']}
    - {role: racket, tags: ['racket']}
    - {role: science, tags: ['science']}
    - {role: shell, tags: ['shell']}
    - {role: text, tags: ['text']}
