---

- hosts: localhost

  pre_tasks:

  - name: create ~/bin directory
    file: name='~/bin' state='directory'
    tags: ['pre', 'directory']

  roles:
    - {role: clang, tags: ['clang', 'system', 'main']}
    - {role: clojure, tags: ['clojure', 'function', 'main']}
    - {role: elixir, tags: ['elixir', 'function']}
    - {role: golang, tags: ['golang', 'system']}
    - {role: graphviz, tags: ['graphviz', 'markup']}
    - {role: groovy, tags: ['groovy', 'website']}
    - {role: haskell, tags: ['haskell', 'function']}
    - {role: hylang, tags: ['hylang', 'function', 'main']}
    - {role: java, tags: ['java', 'system', 'main']}
    - {role: julia, tags: ['julia', 'science']}
    - {role: latex, tags: ['latex', 'markup']}
    - {role: nodejs, tags: ['nodejs', 'website']}
    - {role: plantuml, tags: ['plantuml', 'markup']}
    - {role: python, tags: ['python', 'science', 'main']}
    - {role: racket, tags: ['racket', 'function']}
    - {role: rlang, tags: ['rlang', 'science']}
