---

- hosts: localhost

  pre_tasks:

  - name: prepare pip
    package: name='python3-pip'
    become: true

  - name: prepare bin
    file: name='~/bin/' state='directory'

  roles:
    # documents {{{
    - {role: graphviz, tags: ['graphviz', 'docs']}
    - {role: plantuml, tags: ['plantuml', 'docs']}
    # }}}
    # languages {{{
    - {role: clang, tags: ['clang', 'lang']}
    - {role: python, tags: ['python', 'lang']}
    - {role: tscript, tags: ['tscript', 'lang']}
    # }}}
    # runtimes {{{
    - {role: keras, tags: ['keras', 'run']}
    # }}}
    # services {{{
    - {role: docker, tags: ['docker', 'srv']}
    # }}}
