---

- name: keyring
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
  become: true
  tags: admin

- name: repository
  apt_repository:
    filename: vscode
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
  become: true
  tags: admin

- name: editor
  package:
    name: code
  become: true
  tags: admin

- name: font
  package:
    name: fonts-firacode
  become: true
  tags: admin

- name: directory
  file:
    state: directory
    name: ~/.config/Code/User
  tags: user

- name: snippets
  file:
    force: yes
    state: link
    dest: ~/.config/Code/User/snippets
    src: "{{ role_path }}/files/snippets"
  tags: user

- name: settings
  file:
    force: yes
    state: link
    dest: ~/.config/Code/User/settings.json
    src: "{{ role_path }}/files/settings.json"
  tags: user

- name: keybindings
  file:
    force: yes
    state: link
    dest: ~/.config/Code/User/keybindings.json
    src: "{{ role_path }}/files/keybindings.json"
  tags: user

- name: extensions
  shell: code --install-extension {{ item|quote }}
  with_items:
#     - VisualStudioExptTeam.vscodeintellicode
#     - alefragnani.Bookmarks
#     - christian-kohler.path-intellisense
    - dchanco.vsc-invoke
    - jebbs.plantuml
    - lextudio.restructuredtext
    - ms-python.python
#     - ryu1kn.edit-with-shell
    - streetsidesoftware.code-spell-checker
    - vscodevim.vim
  tags: user
