---

- name: language
  package:
    name: leiningen
  become: true
  tags: admin

- name: directory
  file:
    state: directory
    path: ~/.lein/
    mode: 0750
  tags: user

- name: config
  file:
    force: yes
    state: link
    dest: ~/.lein/profiles.clj
    src: "{{ role_path }}/files/profiles.clj"
  tags: user
