---

- name: language
  package:
    name: leiningen
  become: true
  tags: admin

- name: directory
  file:
    state: directory
    path: ~/.lein/
    mode: 0750
  tags: user

- name: config
  file:
    src: "{{ role_path }}/files/profiles.clj"
    dest: ~/.lein/profiles.clj
    state: link
    force: yes
  tags: user
