---

- name: keyring
  ansible.builtin.apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
  become: true
  tags: admin

- name: repository
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_19.x {{ ansible_distribution_release }} main"
    filename: nodejs
  become: true
  tags: admin

- name: package
  ansible.builtin.package:
    name: nodejs
  become: true
  tags: admin

- name: config
  ansible.builtin.file:
    src: "{{ role_path }}/files/npmrc"
    dest: ~/.npmrc
    state: link
    force: yes
  tags: user
