---

- name: keyring
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
  become: true
  tags: admin

- name: repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_17.x {{ ansible_distribution_release }} main"
    filename: nodejs
  become: true
  tags: admin

- name: package
  package:
    name: nodejs
  become: true
  tags: admin

- name: config
  file:
    src: "{{ role_path }}/files/npmrc"
    dest: ~/.npmrc
    state: link
    force: yes
  tags: user
