---

- name: keyring
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
  become: true
  tags: admin

- name: repository
  apt_repository:
    filename: nodejs
    repo: "deb https://deb.nodesource.com/node_14.x focal main"
  become: true
  tags: admin

- name: package
  package:
    name: nodejs
  become: true
  tags: admin

- name: config
  file:
    force: yes
    state: link
    dest: ~/.npmrc
    src: "{{ role_path }}/files/npmrc"
  tags: user
