---

- name: package
  package:
    name: python3-dev
  become: true
  tags: admin

- name: manager
  package:
    name: python3-pip
  become: true
  tags: admin

- name: environ
  package:
    name: python3-venv
  become: true
  tags: admin

- name: environ
  package:
    name: python-dev-is-python3
  become: true
  tags: admin

- name: maker
  pip:
    name: invoke
    executable: pip3
    extra_args: --user
  tags: user

- name: typer
  pip:
    name: mypy
    executable: pip3
    extra_args: --user
  tags: user

- name: linter
  pip:
    name: pylint
    executable: pip3
    extra_args: --user
  tags: user

- name: sorter
  pip:
    name: isort
    executable: pip3
    extra_args: --user
  tags: user

- name: tester
  pip:
    name: pytest
    executable: pip3
    extra_args: --user
  tags: user

- name: unuser
  pip:
    name: vulture
    executable: pip3
    extra_args: --user
  tags: user

- name: coverer
  pip:
    name: coverage
    executable: pip3
    extra_args: --user
  tags: user

- name: checker
  pip:
    name: bandit
    executable: pip3
    extra_args: --user
  tags: user

- name: compiler
  pip:
    name: cython
    executable: pip3
    extra_args: --user
  tags: user

- name: debugger
  pip:
    name: ipdb
    executable: pip3
    extra_args: --user
  tags: user

- name: packager
  pip:
    name: wheel
    executable: pip3
    extra_args: --user
  tags: user

- name: profiler
  pip:
    name: profiling
    executable: pip3
    extra_args: --user
  tags: user

- name: uploader
  pip:
    name: twine
    executable: pip3
    extra_args: --user
  tags: user

- name: completer
  pip:
    name: jedi
    executable: pip3
    extra_args: --user
  tags: user

- name: formatter
  pip:
    name: black
    executable: pip3
    extra_args: --user
  tags: user

- name: docstyler
  pip:
    name: pydocstyle
    executable: pip3
    extra_args: --user
  tags: user

- name: documenter
  pip:
    name: pdoc
    executable: pip3
    extra_args: --user
  tags: user

- name: refactorer
  pip:
    name: rope
    executable: pip3
    extra_args: --user
  tags: user

- name: prototyper
  pip:
    name: streamlit
    executable: pip3
    extra_args: --user
  tags: user

- name: interpreter
  pip:
    name: ipython
    executable: pip3
    extra_args: --user
  tags: user

- name: hosting
  file:
    force: yes
    state: link
    dest: ~/.pypirc
    src: "{{ role_path }}/files/pypirc"
  tags: user

- name: config
  git:
    repo: https://github.com/fmind/ipython.d
    dest: ~/.ipython
  tags: user
