---

- name: language
  package: name='python3-dev'
  become: true
  tags: admin

- name: manager
  package: name='python3-pip'
  become: true
  tags: admin

- name: sandbox
  package: name='python3-venv'
  become: true
  tags: admin

- name: maker
  package: name='make'
  become: true
  tags: admin

- name: typer
  pip: name='mypy' executable='pip3' extra_args='--user'
  tags: user

- name: sorter
  pip: name='isort' executable='pip3' extra_args='--user'
  tags: user

- name: linter
  pip: name='pylint' executable='pip3' extra_args='--user'
  tags: user

- name: tester
  pip: name='pytest' executable='pip3' extra_args='--user'
  tags: user

- name: packager
  pip: name='wheel' executable='pip3' extra_args='--user'
  tags: user

- name: uploader
  pip: name='twine' executable='pip3' extra_args='--user'
  tags: user

- name: formatter
  pip: name='black' executable='pip3' extra_args='--user'
  tags: user

- name: directory
  file: path='~/.ptpython/' state='directory'
  tags: user

- name: input
  pip: name='ptpython' executable='pip3' extra_args='--user'
  tags: user

- name: config
  file: src='{{role_path}}/files/ptpython.py' dest='~/.ptpython/config.py' state=link force=yes
  tags: user

- name: hosting
  file: src='{{role_path}}/files/pypirc' dest='~/.pypirc' state=link force=yes
  tags: user
