---

- name: package
  package:
    name: python3-dev
  become: true
  tags: admin

- name: manager
  package:
    name: python3-pip
  become: true
  tags: admin

- name: sandbox
  package:
    name: python3-venv
  become: true
  tags: admin

- name: maker
  pip:
    name: invoke
    executable: pipx
  tags: user

- name: typer
  pip:
    name: mypy
    executable: pipx
  tags: user

- name: linter
  pip:
    name: pylint
    executable: pipx
  tags: user

- name: sorter
  pip:
    name: isort
    executable: pipx
  tags: user

- name: tester
  pip:
    name: pytest
    executable: pipx
  tags: user

- name: unsued
  pip:
    name: vulture
    executable: pipx
  tags: user

- name: coverer
  pip:
    name: coverage
    executable: pipx
  tags: user

- name: compiler
  pip:
    name: cython
    executable: pipx
  tags: user

- name: debugger
  pip:
    name: ipdb
    executable: pipx
  tags: user

- name: packager
  pip:
    name: wheel
    executable: pip3
    extra_args: --user
  tags: user

- name: profiler
  pip:
    name: profiling
    executable: pipx
  tags: user

- name: security
  pip:
    name: bandit
    executable: pipx
  tags: user

- name: uploader
  pip:
    name: twine
    executable: pipx
  tags: user

- name: completer
  pip:
    name: jedi
    executable: pip3
    extra_args: --user
  tags: user

- name: formatter
  pip:
    name: black
    executable: pipx
  tags: user

- name: installer
  pip:
    name: pyinstaller
    executable: pipx
  tags: user

- name: documenter
  pip:
    name: pdoc
    executable: pipx
  tags: user

- name: refactorer
  pip:
    name: bowler
    executable: pipx
  tags: user

- name: interpreter
  pip:
    name: ipython
    executable: pipx
  tags: user

- name: directory
  file:
    state: directory
    path: ~/.ipython/profile_default/
  tags: user

- name: hosting
  file:
    force: yes
    state: link
    dest: ~/.pypirc
    src: "{{ role_path }}/files/pypirc"
  tags: user

- name: config
  file:
    force: yes
    state: link
    dest: ~/.ipython/profile_default/ipython_config.py
    src: "{{ role_path }}/files/ipython.py"
  tags: user
