---

- name: package
  ansible.builtin.package:
    name: python3-dev
  become: true
  tags: admin

- name: manager
  ansible.builtin.package:
    name: python3-pip
  become: true
  tags: admin

- name: environ
  ansible.builtin.package:
    name: python3-venv
  become: true
  tags: admin

- name: project
  community.general.pipx:
    name: poetry
  tags: user

- name: maker
  community.general.pipx:
    name: invoke
  tags: user

- name: interpreter
  community.general.pipx:
    name: ipython
  tags: user

- name: hosting
  ansible.builtin.file:
    src: "{{ role_path }}/files/pypirc"
    dest: ~/.pypirc
    state: link
    force: yes
  tags: user

- name: config
  git:
    repo: https://github.com/fmind/ipython.d
    dest: ~/.ipython
    depth: 1
  tags: user
