---

- name: install dependencies
  package: name='{{item}}'
  with_items:
    - llvm
    - make
    - xz-utils
    - zlib1g-dev
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libpython-dev
    - libpython3-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - python3-zmq
  become: true

- name: install package
  package: name='python3'
  become: true

- name: install manager
  package: name='{{item}}'
  with_items:
    - python3-pip
    - python3-venv
  become: true

- name: install librairies
  pip: name='{{item}}' executable='pip3' extra_args='--user'
  with_items:
    - ipdb
    - jedi
    - wheel
    - twine
    - ipython
    - notebook
    - jupyterlab
  tags: ['usr']

- name: install version
  git: repo='https://github.com/pyenv/pyenv.git' dest='~/.pyenv' depth=1
  tags: ['usr']

- name: deploy hosting
  file: src='files/pypirc' dest='~/.pypirc' state=link force=yes
  tags: ['usr']

- name: create directory
  file: path='~/.ipython/profile_default/' state='directory'
  tags: ['usr']

- name: deploy config
  file: src='files/ipython.py' dest='~/.ipython/profile_default/ipython_config.py' state=link force=yes
  tags: ['usr']
