---

- name: package
  package:
    name: python3-dev
  become: true
  tags: admin

- name: manager
  package:
    name: python3-pip
  become: true
  tags: admin

- name: environ
  package:
    name: python3-venv
  become: true
  tags: admin

- name: project
  pip:
    name: poetry
    executable: pip3
    extra_args: --user
  tags: user

- name: interpreter
  pip:
    name: ipython
    executable: pip3
    extra_args: --user
  tags: user

- name: hosting
  file:
    src: "{{ role_path }}/files/pypirc"
    dest: ~/.pypirc
    state: link
    force: yes
  tags: user

- name: config
  git:
    repo: https://github.com/fmind/ipython.d
    dest: ~/.ipython
  tags: user
