---

- name: framework
  pip:
    name: tensorflow
    executable: pip3
    extra_args: --user
  tags: user

- name: hub
  pip:
    name: tensorflow_hub
    executable: pip3
    extra_args: --user
  tags: user

- name: cloud
  pip:
    name: tensorflow-cloud
    executable: pip3
    extra_args: --user
  tags: user

- name: tuner
  pip:
    name: autokeras
    executable: pip3
    extra_args: --user
  tags: user

- name: monitor
  pip:
    name: tensorboard
    executable: pip3
    extra_args: --user
  tags: user

- name: storage
  pip:
    name: feast
    executable: pip3
    extra_args: --user
  tags: user

- name: datasets
  pip:
    name: tensorflow-datasets
    executable: pip3
    extra_args: --user
  tags: user

- name: pipeline
  pip:
    name: tfx
    executable: pip3
    extra_args: --user
  tags: user

- name: explorer
  pip:
    name: witwidget
    executable: pip3
    extra_args: --user
  tags: user
