---

- name: keyring
  apt_key: url='https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub'
  become: true
  tags: admin

- name: graphics
  apt_repository: repo='ppa:graphics-drivers/ppa' filename='drivers'
  become: true
  tags: admin

- name: learning
  apt_repository: repo='deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/ /' filename='learning'
  become: true
  tags: admin

- name: cuda
  apt_repository: repo='deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /' filename='cuda'
  become: true
  tags: admin

- name: dependencies
  package: name='{{item}}'
  with_items:
    - cuda
    - libcudnn7
    - libnvinfer5
    - libcudnn7-dev
    - libnvinfer-dev
    - nvidia-driver-418
  become: true
  tags: admin

- name: packages
  pip: name='{{item}}' executable='pip3' extra_args='--user'
  with_items:
    - tensorflow>=2.0.0
    - tensorflow-hub
    - tensorflow-datasets
    - tensorflow-probability
  tags: user
