---

- name: keyring
  apt_key:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
  become: true
  tags: admin

- name: graphic
  apt_repository:
    filename: drivers
    repo: ppa:graphics-drivers/ppa
  become: true
  tags: admin

- name: learning
  apt_repository:
    filename: learning
    repo: "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/ /"
  become: true
  tags: admin

- name: repository
  apt_repository:
    filename: cuda
    repo: "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
  become: true
  tags: admin

- name: driver
  package:
    name: nvidia-driver-418
  become: true
  tags: admin

- name: libraries
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
      - cuda-10-0
      - libcudnn7
      - libnvinfer5
      - libcudnn7-dev
      - libnvinfer-dev
  become: true
  tags: admin

- name: packages
  pip:
    name:
      - tensorflow-gpu>=2.0.0
      - tensorflow-hub
      - tensorflow-datasets
      - tensorflow-probability
    executable: pip3
    extra_args: --user
  tags: user
