---

- name: language
  package: name='build-essential'
  become: true
  tags: admin

- name: tagger
  package: name='exuberant-ctags'
  become: true
  tags: admin

- name: maker
  package: name='cmake'
  become: true
  tags: admin

- name: config
  file: src='{{role_path}}/files/ctags' dest='~/.ctags' state=link force=yes
  tags: user
