---

- name: language
  package: name='julia'
  become: true
  tags: admin

- name: directory
  file: path='~/.julia/config' state='directory'
  tags: user

- name: config
  file: src='{{role_path}}/files/startup.jl' dest='~/.julia/config/startup.jl' state=link force=yes
  tags: user
