---

- name: language
  package: name='haskell-stack'
  become: true
  tags: admin

- name: directory
  file: path='~/.stack/' state='directory'
  tags: user

- name: config
  file: src='{{role_path}}/files/config.yaml' dest='~/.stack/config.yaml' state=link force=yes
  tags: user

- name: input
  file: src='{{role_path}}/files/haskeline' dest='~/.haskeline' state=link force=yes
  tags: user
