---

- name: sandbox
  package: name='nodejs'
  become: true
  tags: admin

- name: manager
  package: name='npm'
  become: true
  tags: admin

- name: language
  npm: name='typescript' global=yes
  become: true
  tags: admin

- name: config
  file: src='{{role_path}}/files/npmrc' dest='~/.npmrc' state=link force=yes
  tags: user
