---

- name: keyring
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
  become: true
  tags: admin

- name: repository
  apt_repository:
    filename: learning
    repo: "deb https://deb.nodesource.com/node_14.x focal main"
  become: true
  tags: admin

- name: dependencies
  package:
    name: nodejs
  become: true
  tags: admin

- name: maker
  pip:
    name: papermill
    executable: pip3
    extra_args: --user
  tags: user

- name: differ
  pip:
    name: nbdime
    executable: pip3
    extra_args: --user
  tags: user

- name: reader
  pip:
    name: nbformat
    executable: pip3
    extra_args: --user
  tags: user

- name: editor
  pip:
    name: jupyterlab
    executable: pip3
    extra_args: --user
  tags: user

- name: plotter
  pip:
    name: jupyter-dash
    executable: pip3
    extra_args: --user
  tags: user

- name: widgets
  pip:
    name: ipywidgets
    executable: pip3
    extra_args: --user
  tags: user

- name: storage
  pip:
    name: feast
    executable: pip3
    extra_args: --user
  tags: user

- name: parallels
  pip:
    name: ray
    executable: pip3
    extra_args: --user
  tags: user

- name: executor
  pip:
    name: prefect
    executable: pip3
    extra_args: --user
  tags: user

- name: framework
  pip:
    name: tfx
    executable: pip3
    extra_args: --user
  tags: user

- name: graphics
  pip:
    name: jupyterlab-drawio
    executable: pip3
    extra_args: --user
  tags: user

- name: dashboard
  pip:
    name: voila
    executable: pip3
    extra_args: --user
  tags: user

- name: explorer
  pip:
    name: witwidget
    executable: pip3
    extra_args: --user
  tags: user

- name: completer
  pip:
    name: jupyterlab-lsp
    executable: pip3
    extra_args: --user
  tags: user

- name: presenter
  pip:
    name: RISE
    executable: pip3
    extra_args: --user
  tags: user

- name: formatter
  pip:
    name: jupyterlab_code_formatter
    executable: pip3
    extra_args: --user
  tags: user

- name: monitorer
  pip:
    name: tensorboard
    executable: pip3
    extra_args: --user
  tags: user

- name: transformer
  pip:
    name: jupytext
    executable: pip3
    extra_args: --user
  tags: user

- name: versioning
  pip:
    name: jupyterlab-git
    executable: pip3
    extra_args: --user
  tags: user

- name: resourcing
  pip:
    name: jupyter-resource-usage
    executable: pip3
    extra_args: --user
  tags: user

- name: spellchecker
  pip:
    name: jupyterlab-spellchecker
    executable: pip3
    extra_args: --user
  tags: user

- name: completion
  pip:
    name: python-lsp-server[all]
    executable: pip3
    extra_args: --user
  tags: user

- name: config
  git:
    repo: https://github.com/fmind/jupyter.d
    dest: ~/.jupyter
  tags: user
