---

- name: dependencies
  package:
    name: "{{ item }}"
  with_items:
    - nodejs
  become: true
  tags: admin

- name: editor
  pip:
    name: jupyterlab
    executable: pip3
    extra_args: --user
  tags: user

- name: maker
  pip:
    name: papermill
    executable: pip3
    extra_args: --user
  tags: user

- name: tester
  pip:
    name: testbook
    executable: pip3
    extra_args: --user
  tags: user

- name: plotter
  pip:
    name: jupyter-dash
    executable: pip3
    extra_args: --user
  tags: user

- name: widgets
  pip:
    name: ipywidgets
    executable: pip3
    extra_args: --user
  tags: user

- name: storage
  pip:
    name: feast
    executable: pip3
    extra_args: --user
  tags: user

- name: parallel
  pip:
    name: ipyparallel
    executable: pip3
    extra_args: --user
  tags: user

- name: framework
  pip:
    name: tfx
    executable: pip3
    extra_args: --user
  tags: user

- name: developer
  pip:
    name: nbdev
    executable: pip3
    extra_args: --user
  tags: user

- name: graphics
  pip:
    name: jupyterlab-drawio
    executable: pip3
    extra_args: --user
  tags: user

- name: dashboard
  pip:
    name: voila
    executable: pip3
    extra_args: --user
  tags: user

- name: converter
  pip:
    name: scrapbook
    executable: pip3
    extra_args: --user
  tags: user

- name: explorer
  pip:
    name: witwidget
    executable: pip3
    extra_args: --user
  tags: user

- name: presenter
  pip:
    name: RISE
    executable: pip3
    extra_args: --user
  tags: user

- name: formatter
  pip:
    name: nbformat
    executable: pip3
    extra_args: --user
  tags: user

- name: workspace
  pip:
    name: elyra
    executable: pip3
    extra_args: --user
  tags: user

- name: monitorer
  pip:
    name: tensorboard
    executable: pip3
    extra_args: --user
  tags: user

- name: prototyper
  pip:
    name: streamlit
    executable: pip3
    extra_args: --user
  tags: user

- name: transformer
  pip:
    name: jupytext
    executable: pip3
    extra_args: --user
  tags: user

- name: config
  git:
    repo: https://github.com/fmind/jupyter.d
    dest: ~/.jupyter
  tags: user
