---

- name: editor
  pip:
    name: jupyterlab
    executable: pip3
    extra_args: --user
  tags: user

- name: text
  pip:
    name: jupytext
    executable: pip3
    extra_args: --user
  tags: user

- name: maker
  pip:
    name: papermill
    executable: pip3
    extra_args: --user
  tags: user

- name: widgets
  pip:
    name: ipywidgets
    executable: pip3
    extra_args: --user
  tags: user

- name: parallel
  pip:
    name: ipyparallel
    executable: pip3
    extra_args: --user
  tags: user

- name: dashboard
  pip:
    name: voila
    executable: pip3
    extra_args: --user
  tags: user

- name: scheduler
  pip:
    name: joblib
    executable: pip3
    extra_args: --user
  tags: user

- name: developer
  pip:
    name: streamlit
    executable: pip3
    extra_args: --user
  tags: user

- name: directory
  file:
    state: directory
    path: ~/.jupyter/
  tags: user

- name: config
  file:
    force: yes
    state: link
    dest: ~/.jupyter/jupyter_notebook_config.py
    src: "{{ role_path }}/files/jupyter_notebook_config.py"
  tags: user
