---

- name: editor
  pip:
    name: jupyterlab
    executable: pip3
    extra_args: --user
  notify: Build jupyter lab
  tags: user

- name: maker
  pip:
    name: papermill
    executable: pip3
    extra_args: --user
  tags: user

- name: transformer
  pip:
    name: jupytext
    executable: pip3
    extra_args: --user
  notify: Build jupyter lab
  tags: user

- name: config
  git:
    repo: https://github.com/fmind/jupyter.d
    dest: ~/.jupyter
  tags: user
