---

- name: maker
  pip:
    name: papermill
    executable: pip3
    extra_args: --user
  tags: user

- name: differ
  pip:
    name: nbdime
    executable: pip3
    extra_args: --user
  tags: user

- name: reader
  pip:
    name: nbformat
    executable: pip3
    extra_args: --user
  tags: user

- name: editor
  pip:
    name: jupyterlab
    executable: pip3
    extra_args: --user
  tags: user

- name: plotter
  pip:
    name: jupyter-dash
    executable: pip3
    extra_args: --user
  tags: user

- name: widgets
  pip:
    name: ipywidgets
    executable: pip3
    extra_args: --user
  tags: user

- name: storage
  pip:
    name: feast
    executable: pip3
    extra_args: --user
  tags: user

- name: monitor
  pip:
    name: tensorboard
    executable: pip3
    extra_args: --user
  tags: user

- name: executor
  pip:
    name: prefect
    executable: pip3
    extra_args: --user
  tags: user

- name: parallels
  pip:
    name: dask
    executable: pip3
    extra_args: --user
  tags: user

- name: framework
  pip:
    name: tfx
    executable: pip3
    extra_args: --user
  tags: user

- name: dashboard
  pip:
    name: voila
    executable: pip3
    extra_args: --user
  tags: user

- name: explorer
  pip:
    name: witwidget
    executable: pip3
    extra_args: --user
  tags: user

- name: presenter
  pip:
    name: RISE
    executable: pip3
    extra_args: --user
  tags: user

- name: transformer
  pip:
    name: jupytext
    executable: pip3
    extra_args: --user
  tags: user

- name: config
  git:
    repo: https://github.com/fmind/jupyter.d
    dest: ~/.jupyter
  tags: user
