---

- name: dependencies
  package:
    name: "{{ item }}"
  with_items:
    - npm
    - nodejs
  become: true
  tags: admin

- name: editor
  pip:
    name: jupyterlab
    executable: pip3
    extra_args: --user
  tags: user

- name: maker
  pip:
    name: papermill
    executable: pip3
    extra_args: --user
  tags: user

- name: widgets
  pip:
    name: ipywidgets
    executable: pip3
    extra_args: --user
  tags: user

- name: parallel
  pip:
    name: ipyparallel
    executable: pip3
    extra_args: --user
  tags: user

- name: dashboard
  pip:
    name: voila
    executable: pip3
    extra_args: --user
  tags: user

- name: pipeliner
  pip:
    name: metaflow
    executable: pip3
    extra_args: --user
  tags: user

- name: converter
  pip:
    name: jupytext
    executable: pip3
    extra_args: --user
  tags: user

- name: presenter
  pip:
    name: RISE
    executable: pip3
    extra_args: --user
  tags: user

- name: scheduler
  pip:
    name: apache-airflow
    executable: pip3
    extra_args: --user
  tags: user

- name: prototyper
  pip:
    name: streamlit
    executable: pip3
    extra_args: --user
  tags: user

- name: workflower
  pip:
    name: mlflow
    executable: pip3
    extra_args: --user
  tags: user

- name: directory
  file:
    state: directory
    path: ~/.jupyter/
  tags: user

- name: hosting
  file:
    force: yes
    state: link
    dest: ~/.jupyter/jupyter_notebook_config.py
    src: "{{ role_path }}/files/jupyter_notebook_config.py"
  tags: user
