---

- name: dependencies
  package:
    name: "{{ item }}"
  with_items:
    - nodejs
  become: true
  tags: admin

- name: editor
  pip:
    name: jupyterlab
    executable: pip3
    extra_args: --user
  tags: user

- name: maker
  pip:
    name: papermill
    executable: pip3
    extra_args: --user
  tags: user

- name: widgets
  pip:
    name: ipywidgets
    executable: pip3
    extra_args: --user
  tags: user

- name: parallel
  pip:
    name: ipyparallel
    executable: pip3
    extra_args: --user
  tags: user

- name: dashboard
  pip:
    name: voila
    executable: pip3
    extra_args: --user
  tags: user

- name: converter
  pip:
    name: nbconvert
    executable: pip3
    extra_args: --user
  tags: user

- name: presenter
  pip:
    name: RISE
    executable: pip3
    extra_args: --user
  tags: user

- name: nbscraper
  pip:
    name: nteract-scrapbook
    executable: pip3
    extra_args: --user
  tags: user

- name: formatter
  pip:
    name: nbformat
    executable: pip3
    extra_args: --user
  tags: user

- name: prototyper
  pip:
    name: streamlit
    executable: pip3
    extra_args: --user
  tags: user

- name: transformer
  pip:
    name: jupytext
    executable: pip3
    extra_args: --user
  tags: user
