---

- name: service
  package:
    name: docker.io
  become: true
  tags: admin

- name: user
  user:
    append: yes
    groups: docker
    name: "{{ lookup('env', 'USER') }}"
  become: true
  tags: admin

- name: compose
  pip:
    name: docker-compose
    executable: pip3
    extra_args: --user
  tags: user
