---

- name: language
  package: name='texlive'
  become: true
  tags: admin

- name: libraries
  package: name='{{item}}'
  with_items:
    - texlive-science
    - texlive-pictures
    - texlive-extra-utils
  become: true
  tags: admin

- name: maker
  package: name='latexmk'
  become: true
  tags: admin

- name: linter
  package: name='chktex'
  become: true
  tags: admin

- name: config
  file: src='{{role_path}}/files/latexmkrc' dest='~/.latexmkrc' state=link force=yes
  tags: user
