---

- name: language
  package:
    name: texlive
  become: true
  tags: admin

- name: libraries
  package:
    name: "{{ packages }}"
  vars:
    packages:
      - texlive-science
      - texlive-pictures
      - texlive-extra-utils
      - texlive-latex-extra
      - texlive-bibtex-extra
  become: true
  tags: admin

- name: maker
  package:
    name: latexmk
  become: true
  tags: admin

- name: linter
  package:
    name: chktex
  become: true
  tags: admin

- name: config
  file:
    force: yes
    state: link
    dest: ~/.latexmkrc
    src: "{{ role_path }}/files/latexmkrc"
  tags: user
