---

- name: install package
  package: name='texlive'
  become: true
  tags: admin

- name: install librairy
  package: name='{{item}}'
  with_items:
    - texlive-science
    - texlive-pictures
  become: true
  tags: admin

- name: install checkers
  package: name='{{item}}'
  with_items:
    - chktex
    - lacheck
  become: true
  tags: admin

- name: install latexmk
  package: name='latexmk'
  become: true
  tags: admin

- name: deploy config
  file: src='{{role_path}}/files/latexmkrc' dest='~/.latexmkrc' state='link' force=true
  tags: user
