---

- name: repository
  apt_repository:
    filename: racket
    repo: ppa:plt/racket
  become: true
  tags: admin

- name: package
  package:
    name: racket
  become: true
  tags: admin

- name: config
  file:
    force: yes
    state: link
    dest: ~/.racketrc
    src: "{{ role_path }}/files/racketrc"
  tags: user
