---

- name: repository
  apt_repository:
    repo: ppa:plt/racket
    filename: racket
  become: true
  tags: admin

- name: package
  package:
    name: racket
  become: true
  tags: admin

- name: config
  file:
    src: "{{ role_path }}/files/racketrc"
    dest: ~/.racketrc
    state: link
    force: yes
  tags: user
