---

- name: add repository
  apt_repository: repo='ppa:plt/racket'
  become: true
  tags: admin

- name: install package
  package: name='racket'
  become: true
  tags: admin

- name: deploy config
  file: src='{{role_path}}/files/racketrc' dest='~/.racketrc' state=link force=yes
  tags: user
